---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.20
  armv7: ghcr.io/home-assistant/armv7-base:3.20
  aarch64: ghcr.io/home-assistant/aarch64-base:3.20
  armhf: ghcr.io/home-assistant/armhf-base:3.20
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Blocky"
  org.opencontainers.image.description: "Fast and lightweight DNS proxy and ad-blocker"
  org.opencontainers.image.source: "https://github.com/robocopklaus/hassio-addon-blocky"
  org.opencontainers.image.licenses: "MIT"
